optionsFile: null
printHelp: false
# WebGoat libs
classPath: []
appClassPath:
  - benchmarks/onemall/management-web-app/BOOT-INF/management-web-app.jar
  - benchmarks/onemall/pay-service-app/BOOT-INF/pay-service-app.jar
  - benchmarks/onemall/product-service-app/BOOT-INF/product-service-app.jar
  - benchmarks/onemall/promotion-service-app/BOOT-INF/promotion-service-app.jar
  - benchmarks/onemall/search-service-app/BOOT-INF/search-service-app.jar
  - benchmarks/onemall/shop-web-app/BOOT-INF/shop-web-app.jar
  - benchmarks/onemall/system-service-app/BOOT-INF/system-service-app.jar
  - benchmarks/onemall/trade-service-app/BOOT-INF/trade-service-app.jar
  - benchmarks/onemall/user-service-app/BOOT-INF/user-service-app.jar

mainClass:
inputClasses: []
javaVersion: 17
prependJVM: true
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile: null
analyses:
  #  ir-dumper: ""
  routerAnalysis: ""
  beanAnalysis: ""
  injectPointsAnalysis: ""
  aspectAnalysis: ""
  cg: ""
  #  cfg: ""
  #  icfg: ""
  pta: "plugins:[org.example.spring.plugin.ProcessDIPlugin,org.example.spring.plugin.ProcessEntryPlugin,org.example.spring.plugin.ProcessAspectPlugin]"
#  pta: "plugins:[org.example.spring.plugin.ProcessEntryPlugin]"
onlyGenPlan: false
keepResult:
  - $KEEP-ALL