optionsFile: null
printHelp: false
# WebGoat libs
classPath: []
appClassPath:
  - benchmarks/mogu/mogu_admin-0.0.1-SNAPSHOT/BOOT-INF/mogu_admin-0.0.1-SNAPSHOT.jar
  - benchmarks/mogu/mogu_gateway-0.0.1-SNAPSHOT/BOOT-INF/mogu_gateway-0.0.1-SNAPSHOT.jar
  - benchmarks/mogu/mogu_monitor-0.0.1-SNAPSHOT/BOOT-INF/mogu_monitor-0.0.1-SNAPSHOT.jar
  - benchmarks/mogu/mogu_picture-0.0.1-SNAPSHOT/BOOT-INF/mogu_picture-0.0.1-SNAPSHOT.jar
  - benchmarks/mogu/mogu_search-0.0.1-SNAPSHOT/BOOT-INF/mogu_search-0.0.1-SNAPSHOT.jar
  - benchmarks/mogu/mogu_sms-0.0.1-SNAPSHOT/BOOT-INF/mogu_sms-0.0.1-SNAPSHOT.jar
  - benchmarks/mogu/mogu_spider-0.0.1-SNAPSHOT/BOOT-INF/mogu_spider-0.0.1-SNAPSHOT.jar
  - benchmarks/mogu/mogu_web-0.0.1-SNAPSHOT/BOOT-INF/mogu_web-0.0.1-SNAPSHOT.jar

mainClass:
inputClasses: []
javaVersion: 17
prependJVM: true
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile: null
analyses:
  #  ir-dumper: ""
  routerAnalysis: ""
  beanAnalysis: ""
  injectPointsAnalysis: ""
  aspectAnalysis: ""
  cg: ""
  #  cfg: ""
  #  icfg: ""
  pta: "plugins:[org.example.spring.plugin.ProcessDIPlugin,org.example.spring.plugin.ProcessEntryPlugin,org.example.spring.plugin.ProcessAspectPlugin]"
#  pta: "plugins:[org.example.spring.plugin.ProcessEntryPlugin]"
onlyGenPlan: false
keepResult:
  - $KEEP-ALL