optionsFile: null
printHelp: false
# WebGoat libs
classPath: []
appClassPath:
  - /Users/yuntsy/My/Graduate/Data/final/RuoYi/ruoyi-admin/target
  - /Users/yuntsy/My/Graduate/Data/final/RuoYi/ruoyi-common/target
  - /Users/yuntsy/My/Graduate/Data/final/RuoYi/ruoyi-framework/target
  - /Users/yuntsy/My/Graduate/Data/final/RuoYi/ruoyi-generator/target
  - /Users/yuntsy/My/Graduate/Data/final/RuoYi/ruoyi-quartz/target
  - /Users/yuntsy/My/Graduate/Data/final/RuoYi/ruoyi-system/target
mainClass:
inputClasses: []
javaVersion: 17
prependJVM: true
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile: null
analyses:
  #  ir-dumper: ""
  routerAnalysis: ""
  beanAnalysis: ""
  injectPointsAnalysis: ""
  aspectAnalysis: ""
  resultAnalysis: ""
  cg: ""
#  pta: "plugins:[org.example.spring.plugin.ProcessDIPlugin,org.example.spring.plugin.ProcessEntryPlugin,org.example.spring.plugin.ProcessAspectPlugin]"
#  pta: "plugins:[org.example.spring.plugin.ProcessEntryPlugin, org.example.spring.plugin.ProcessDIPlugin]"
#  pta: "plugins:[org.example.spring.plugin.ProcessEntryPlugin]"
onlyGenPlan: false
keepResult:
  - $KEEP-ALL