optionsFile: null
printHelp: false
# WebGoat libs
classPath: []
appClassPath:
  - benchmarks/basemall/gruul-account-open-service/BOOT-INF/gruul-account-open-service.jar
  - benchmarks/basemall/gruul-afs-open-service/BOOT-INF/gruul-afs-open-service.jar
  - benchmarks/basemall/gruul-gateway-open/BOOT-INF/gruul-gateway-open.jar
  - benchmarks/basemall/gruul-goods-open-service/BOOT-INF/gruul-goods-open-service.jar
  - benchmarks/basemall/gruul-logistics-open/BOOT-INF/gruul-logistics-open.jar
  - benchmarks/basemall/gruul-order-open-service/BOOT-INF/gruul-order-open-service.jar
  - benchmarks/basemall/gruul-oss-open-service/BOOT-INF/gruul-oss-open-service.jar
  - benchmarks/basemall/gruul-payment-open-service/BOOT-INF/gruul-payment-open-service.jar
  - benchmarks/basemall/gruul-platform-open-service/BOOT-INF/gruul-platform-open-service.jar
  - benchmarks/basemall/gruul-shops-open-service/BOOT-INF/gruul-shops-open-service.jar
  - benchmarks/basemall/gruul-sms-open-service/BOOT-INF/gruul-sms-open-service.jar

mainClass:
inputClasses: []
javaVersion: 17
prependJVM: true
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile: null
analyses:
  #  ir-dumper: ""
  routerAnalysis: ""
  beanAnalysis: ""
  injectPointsAnalysis: ""
  aspectAnalysis: ""
  cg: ""
  #  cfg: ""
  #  icfg: ""
  pta: "plugins:[org.example.spring.plugin.ProcessEntryPlugin,org.example.spring.plugin.ProcessDIPlugin,org.example.spring.plugin.ProcessAspectPlugin]"
#  pta: "plugins:[org.example.spring.plugin.ProcessEntryPlugin]"
onlyGenPlan: false
keepResult:
  - $KEEP-ALL