sources:
  - kind: param
    method: "<org.example.springtarget.controller.UserController: java.lang.String getUserById(java.lang.String)>"
    index: 0
    type: java.lang.String

sinks:
  - vulnerability: sql-injection
    method: "<java.sql.Statement: java.sql.ResultSet executeQuery(java.lang.String)>"
    index: 0

# 建议添加基础的字符串传递规则，以支持 "SELECT..." + id 这种字符串拼接
transfers:
  - method: "<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>"
    from: 0
    to: base
  - method: "<java.lang.StringBuilder: java.lang.String toString()>"
    from: base
    to: result